version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build:server
      - npm run start:server
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - build/**/*
    - client/**/*
    - deployment/*
    - server/**/*
    - babel.config.js
    - package.json
    - webpack.client.config.js
    - webpack.server.config.js
    - webpack.shared.config.js